spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  sleuth:
    scheduled:
      enabled: false
    sampler:
      percentage: 1
      
server:
  context-path: /uaa
  port: 5000
